


import {
    table,
    hashKey,
    autoGeneratedHashKey,
    attribute,
} from "@aws/dynamodb-data-mapper-annotations";

import { DB_CONFIG } from "@config/db_config";

import GlobalSecondaryIndex from "./IndexGlobal";
const { TABLE_NAME_PREFIX } = DB_CONFIG.DATABASE_CONNECTION;

export enum Visibility{
    PRIVATE = 10,
    WORKSPACE = 20,
    PUBLIC = 30
}

@table(`${TABLE_NAME_PREFIX}board`)
export class Board extends GlobalSecondaryIndex {

    @autoGeneratedHashKey()
    id :string;

    @attribute()
    title :string;


    @attribute()
    workspace_id :string;

    @attribute()
    background_image :string;

    @attribute()
    background_color :string;

    @attribute()
    visibility :Visibility;






}