


import {
    table,
    hashKey,
    autoGeneratedHashKey,
    attribute,
} from "@aws/dynamodb-data-mapper-annotations";

import { DB_CONFIG } from "@config/db_config";
import { generateRandomKeyWithLength } from "@utils/index";

import GlobalSecondaryIndex from "./IndexGlobal";
const { TABLE_NAME_PREFIX } = DB_CONFIG.DATABASE_CONNECTION;


export enum UserStatus{
    UNCONFIRMED = 10,
    CONFIRMED = 20,
    DEACTIVATED = 30
}

export enum MemberType{
    ADMIN = 10,
    COLLABRATOR = 20,
}

@table(`${TABLE_NAME_PREFIX}member`)
export class Member extends GlobalSecondaryIndex {



    @hashKey({defaultProvider: () => generateRandomKeyWithLength(10000).toUpperCase() })
    user_id: string;

    @attribute()
    email: string; // unique

    @attribute()
    first_name: string;

    @attribute()
    last_name: string;

    @attribute()
    picture: string;

    @attribute()
    workspaceId: string;

    @attribute()
    displayName: string;

    @attribute()
    status: UserStatus;

    @attribute()
    type: MemberType


}