/* eslint import/no-cycle: off */

import {
  table,
  attribute,
  autoGeneratedHashKey,
} from "@aws/dynamodb-data-mapper-annotations";
import {
  PerIndexOptions,
  SecondaryIndexOptions,
} from "@aws/dynamodb-data-mapper";

import { DB_CONFIG } from "../config/db_config";

import GlobalSecondaryIndex from "./IndexGlobal";

const { TABLE_NAME_PREFIX } = DB_CONFIG.DATABASE_CONNECTION;

export enum VehicleType {
  COMPACT = "compact",
  NORMAL = "normal",
  LARGE = "large",
}

export type GarageRates = {
  [vehicle_type in VehicleType]: number;
};
@table(`${TABLE_NAME_PREFIX}garage`)
export default class Garage extends GlobalSecondaryIndex {
  @autoGeneratedHashKey()
  ID: string;

  @attribute()
  zipcode: string;

  @attribute()
  rates: GarageRates;

  @attribute({ defaultProvider: () => true })
  is_active: boolean;
}
