/* eslint import/no-cycle: off */

import {
  table,
  attribute,
  autoGeneratedHashKey,
} from "@aws/dynamodb-data-mapper-annotations";
import {
  PerIndexOptions,
  SecondaryIndexOptions,
} from "@aws/dynamodb-data-mapper";

import { DB_CONFIG } from "../config/db_config";

import GlobalSecondaryIndex from "./IndexGlobal";
import { VehicleType } from "./Vehicle";

const { TABLE_NAME_PREFIX } = DB_CONFIG.DATABASE_CONNECTION;

export enum SpotStatus {
  EMPTY = "empty",
  BOOKED = "booked",
}

@table(`${TABLE_NAME_PREFIX}spot`)
export default class Spot extends GlobalSecondaryIndex {
  @autoGeneratedHashKey()
  ID: string;

  @attribute({
    indexKeyConfigurations: {
      garage: "HASH",
    },
  })
  garage_id: string;

  @attribute()
  vehicle_type: VehicleType;

  @attribute({
    indexKeyConfigurations: {
      garage: "RANGE",
    },
  })
  status: SpotStatus;

  public static global_secondary_indices = {
    garage: {
      writeCapacityUnits: 2,
      readCapacityUnits: 2,
      type: "global",
      projection: "all",
    } as SecondaryIndexOptions,
  } as PerIndexOptions;
}
