/* eslint import/no-cycle: off */

import {
  table,
  attribute,
  autoGeneratedHashKey,
} from "@aws/dynamodb-data-mapper-annotations";
import {
  PerIndexOptions,
  SecondaryIndexOptions,
} from "@aws/dynamodb-data-mapper";

import { DB_CONFIG } from "../config/db_config";

import GlobalSecondaryIndex from "./IndexGlobal";

const { TABLE_NAME_PREFIX } = DB_CONFIG.DATABASE_CONNECTION;

export enum VehicleType {
  COMPACT = "compact",
  NORMAL = "normal",
  LARGE = "large",
}

@table(`${TABLE_NAME_PREFIX}vehicle`)
export default class Vehicle extends GlobalSecondaryIndex {
  @autoGeneratedHashKey()
  ID: string;

  @attribute()
  user_id: string;

  @attribute()
  licence_no: string;

  @attribute()
  vehicle_type: VehicleType;

  public static global_secondary_indices = {
    group: {
      writeCapacityUnits: 2,
      readCapacityUnits: 2,
      type: "global",
      projection: "all",
    } as SecondaryIndexOptions,
  } as PerIndexOptions;
}
