
/* eslint import/no-cycle: off */

import {
    table,
    hashKey,
    attribute,
    autoGeneratedHashKey,
  } from "@aws/dynamodb-data-mapper-annotations";
  import { PerIndexOptions, SecondaryIndexOptions } from "@aws/dynamodb-data-mapper";
  
  import { DB_CONFIG } from "../config/db_config";
  
  import GlobalSecondaryIndex from "./IndexGlobal";
  
  import { SPLIT_TYPE} from "@typeroot/models"
  
  const { TABLE_NAME_PREFIX } = DB_CONFIG.DATABASE_CONNECTION;
  
  @table(`${TABLE_NAME_PREFIX}group`)
  export default class Group extends GlobalSecondaryIndex {
      @autoGeneratedHashKey()
      ID: string;

      @attribute()
      name: string;

      @attribute()
      admin: string;

      @attribute()
      members: Array<string>;

      @attribute({defaultProvider: () => Date.now()})
      created_at: number;
  
      @attribute()
      updated_at: number;
  
  }
  