
/* eslint import/no-cycle: off */

import {
    table,
    autoGeneratedHashKey,
    attribute,
} from "@aws/dynamodb-data-mapper-annotations";

import { DB_CONFIG } from "@config/db_config";

import GlobalSecondaryIndex from "./IndexGlobal";
import { generateRandomKeyWithLength } from "../utils/index";
import { PerIndexOptions, SecondaryIndexOptions } from "@aws/dynamodb-data-mapper";
import { Location } from "@typeroot/models";


const { TABLE_NAME_PREFIX } = DB_CONFIG.DATABASE_CONNECTION;

@table(`${TABLE_NAME_PREFIX}restaurant`)
export default class Restaurant extends GlobalSecondaryIndex {
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    name: string;

    @attribute()
    address_id: string;

    @attribute()
    contact?: string;

    @attribute()
    ratings: string;

    @attribute()
    totalRatings: number;

    @attribute()
    cuisines: Array<string>; //["American", "Fast Food"] or ["Fast Food", "Beverages", "Bengali", "Biryani", "Indian", "North Indian", "Snacks", "Street Food"]

    @attribute()
    discount?: number;

    @attribute()
    costForTwo: number;

    @attribute()
    picture: string;

    // menu has index with restaurant_id as primary key, query that for menu

}
